# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcc7945a31292ec7baf9c7377293816da8171d087225c54a51c8c4af74a35f29a88675049ba5b577e4639c446348db4d253b091fde3987746159e78b2d4c2a43

test:
  secret_key_base: 74f6e229235e55b26ce9ead6ae1c3d1ae55046b20f88eb779962b6f908349225848b5f404d1d06e084afb730c96ff2f14372a1818ef8625a4d03e630118a1a5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
